/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jnidemo_iii_JniUntil */

#ifndef _Included_com_jnidemo_iii_JniUntil
#define _Included_com_jnidemo_iii_JniUntil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnidemo_iii_JniUntil
 * Method:    askByJni
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jnidemo_1iii_JniUntil_askByJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
